import { ArrowUpRight, Folder, FolderGit2, FolderPlus, GitBranch, Pin, Search, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { ProjectRecord, ProjectSortMode } from '@/types/api'
import { formatRelative } from '@/lib/data'
import { useI18n } from '@/lib/i18n'
import { EmptyState, IconButton, Modal } from '@/components/ui'
import { sortProjects } from '@/lib/project-order'

export function ProjectsPage({ projects, sortMode, onAdd, onOpen, onRemove, onTogglePin }: { projects: ProjectRecord[]; sortMode: ProjectSortMode; onAdd(): void; onOpen(project: ProjectRecord): void; onRemove(project: ProjectRecord): void; onTogglePin(project: ProjectRecord): void }) {
  const { t } = useI18n()
  const [query, setQuery] = useState('')
  const [removeTarget, setRemoveTarget] = useState<ProjectRecord | null>(null)
  const visible = useMemo(() => sortProjects(projects.filter((project) => `${project.name} ${project.path} ${project.gitBranch ?? ''}`.toLowerCase().includes(query.toLowerCase())), sortMode), [projects, query, sortMode])
  return <div className="page scroll-area"><div className="page-container"><header className="page-header"><div><h1>{t('nav.projects')}</h1><p>{t('projectsPage.description')}</p></div><button type="button" title={t('projectsPage.add')} className="button button--primary" onClick={onAdd}><FolderPlus size={14}/> {t('projectsPage.add')}</button></header><div className="page-tools"><label className="page-search"><Search size={14}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('projectsPage.search')}/></label><span>{t('projectsPage.count', { count: visible.length })}</span></div>{visible.length ? <div className="project-library">{visible.map((project) => <article key={project.id} className="project-item"><button type="button" className="project-item__open" onClick={() => onOpen(project)}><span className="project-item__icon"><FolderGit2 size={19}/></span><span className="project-item__body"><span><h2>{project.name}</h2>{project.pinned ? <Pin size={11} fill="currentColor"/> : null}</span><span className="project-item__path">{project.path}</span><span className="project-item__meta"><span><GitBranch size={12}/>{project.gitBranch ?? t('projectsPage.noRepository')}</span><span>{t('projectsPage.sessionCount', { count: project.sessionCount })}</span><span>{t('projectsPage.opened', { time: formatRelative(project.lastOpenedAt) })}</span></span></span></button><div className="project-item__actions"><IconButton label={t('projectsPage.aria.open', { name: project.name })} onClick={() => onOpen(project)}><ArrowUpRight size={14}/></IconButton>{!project.inferred ? <IconButton label={project.pinned ? t('projectsPage.aria.unpin', { name: project.name }) : t('projectsPage.aria.pin', { name: project.name })} onClick={() => onTogglePin(project)}><Pin size={14} fill={project.pinned ? 'currentColor' : 'none'}/></IconButton> : null}<IconButton label={t('projectsPage.aria.remove', { name: project.name })} onClick={() => setRemoveTarget(project)}><Trash2 size={14}/></IconButton></div></article>)}</div> : <EmptyState icon={<Folder size={25}/>} title={query ? t('projectsPage.empty.noMatch') : t('projectsPage.empty.first')}>{query ? t('projectsPage.empty.hint') : t('projectsPage.empty.chooseFolder')}</EmptyState>}{removeTarget ? <Modal title={t('projectsPage.remove.title')} onClose={() => setRemoveTarget(null)} footer={<><button type="button" className="button" onClick={() => setRemoveTarget(null)}>{t('common.cancel')}</button><button type="button" className="button button--danger" onClick={() => { const project = removeTarget; setRemoveTarget(null); onRemove(project) }}>{t('common.remove')}</button></>}><p>{t('projectsPage.remove.body', { name: removeTarget.name })}</p></Modal> : null}</div></div>
}
